vscode:
  extensions:
    - alygin.vscode-tlaplus@1.5.0:G+Kce8pvXmhitCacF8sdNA==
 
tasks:
  - init: git config --global alias.slog 'log --pretty=oneline --abbrev-commit'
  - init: git config --global alias.co checkout
